# Rules for starting the pipeline
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

    - if: '$CI_COMMIT_TAG'
      when: always

    - changes:
        - "src/**"
        - "pom.xml"
      when: always

    - changes:
        - "README.md"
        - "docs/**"
      when: never

    - when: never

stages:
  - build
  - test

variables:
  PROJECT_NAME: WoT

# Build stage
build-job:
  stage: build
  # Create a container from that image and run it on GitLab
  image: maven:3.9.9-eclipse-temurin-17
  only:
    - main
  script:
    - echo "Building the project..."
    - mvn install

# Test stage
test-job:
  stage: test
  # Create a container from that image and run it on GitLab
  image: maven:3.9.9-eclipse-temurin-17
  only:
    - main
  script:
    - echo "Running unit test in the project..."
    - mvn test
    - mvn checkstyle:checkstyle